Add sync options
ATIX-AG/foreman_scc_manager pull request #111
Opened 2022-10-13 20:11 UTC by sbernhard

2022-10-28 08:04 UTC, m-bucher commented on .github/workflows/unit_tests.yaml
> +        foreman_version: [6.0.43]
That does not look like a `foreman_version` any more :smile:

2022-10-28 08:15 UTC, m-bucher commented on app/models/scc_account.rb
> +  SCC_MIRRORING_POLICY.freeze
Nitpicky, but should it not be `SCC_MIRRORING_POLICIES`!?

2022-10-28 10:41 UTC, m-bucher requested changes
Apart from the small suggestions, this looks good.

2022-10-28 11:18 UTC, m-bucher approved these changes

2022-10-28 12:27 UTC, merged

2022-11-15 12:31 UTC, ekohl reviewed
Bit late to the party, but I was reading through the diff because of a packaging update.

2022-11-15 12:31 UTC, ekohl commented on app/models/scc_account.rb
> +      names.include?(p) ? [names[p], p] : [p, p]
I was reading through this and a more efficient way is to use [fetch](https://ruby-doc.org/core-3.0.1/Array.html#method-i-fetch) with a default value:
```suggestion
      [names.fetch(p, p), p]
```

2022-11-15 12:31 UTC, ekohl commented on app/models/scc_account.rb
> +    names = { 'on_demand' => _('On Demand'), 'immediate' => _('Immediate') }
Looking at https://github.com/Katello/katello/blob/28a7171ed3be4fdb0ebd96bfad2304b05f0ea080/app/helpers/katello/concerns/smart_proxy_helper_extensions.rb#L28-L49 you should use constants such as `::Katello::RootRepository::DOWNLOAD_ON_DEMAND` and `::Katello::RootRepository::DOWNLOAD_IMMEDIATE`.