WIP: Model and migration for 1:n SCC-Katello-Repo association
ATIX-AG/foreman_scc_manager pull request #96
Opened 2022-04-27 11:17 UTC by nadjaheitmann

2022-04-27 13:45 UTC, m-bucher commented on db/migrate/20220425132605_add_scc_katello_repository_relation.rb
> +      t.integer :katello_root_repository_id, null: false
Is it possible to use `t.references`, here? See https://api.rubyonrails.org/v6.0/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-references

2022-05-19 12:00 UTC, m-bucher requested changes
Is there a way we can merge the DB-migrations into a single one?

2022-05-19 12:05 UTC, nadjaheitmann commented on app/lib/actions/scc_manager/subscribe_product.rb
> +          scc_repo.update!(katello_root_repository_ids: scc_repo.katello_root_repository_ids.push(katello_root_repository_id))
Not sure, if this works to be honest... I did not add a reference from root repositories to scc_repositories that could handle this in Rails

2022-05-19 13:48 UTC, m-bucher approved these changes
Squash the commits and it is good to go :smile:

2022-05-20 07:19 UTC, merged